---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/ansible/ansible-lint
    rev: v25.9.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        args: [--fix]
        # ansible is too big for GHA. It affects snap
        # WARNING  Unable to resolve FQCN for module community.general.snap
        additional_dependencies:
          - ansible-core
