Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.gui = false
  end

  # Sync the current project directory to the VM
  config.vm.synced_folder ".", "/home/vagrant/workstation"

  # Provisioning
  config.vm.provision "shell", inline: <<-SHELL
    set -e
    echo "Installing Ansible..."
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y ansible

    echo "Running Ansible Playbook..."
    cd /home/vagrant/workstation
    # Run the playbook. Note: We use -e to pass any needed variables if necessary.
    ansible-playbook local.yml
  SHELL
end
