---
- name: Get home directory
  ansible.builtin.set_fact:
    home_directory: "{{ lookup('env', 'HOME') }}"

- name: Clone dotfiles
  ansible.builtin.git:
    repo: git@github.com:HeySlava/.dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    single_branch: true
    version: main
