---
- name: Download keyring.deb
  ansible.builtin.get_url:
    url: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2025.12.14_all.deb
    dest: /opt/keyring.deb
    checksum: sha256:2c816fbd12ea4d84811818aed0ce3a5da589be1afa30833eb32abc1e4fe6349e
    mode: "0600"
  become: true

- name: Install keyring.deb
  ansible.builtin.apt:
    deb: /opt/keyring.deb
  become: true

- name: Add sur5r repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/sur5r-keyring.gpg] http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe"
    state: present
    filename: sur5r
  become: true

- name: Install i3 window manager
  ansible.builtin.apt:
    name: i3
    state: present
    update_cache: true
  become: true
