---
- name: Download keyring.deb
  ansible.builtin.get_url:
    url: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2024.03.04_all.deb
    dest: /opt/keyring.deb
    checksum: sha256:f9bb4340b5ce0ded29b7e014ee9ce788006e9bbfe31e96c09b2118ab91fca734
    mode: "0600"
  become: true

- name: Install keyring.deb
  ansible.builtin.apt:
    deb: /opt/keyring.deb
  become: true

- name: Add sur5r repository
  ansible.builtin.apt_repository:
    repo: deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe
    state: present
    filename: sur5r
  become: true

- name: Install i3 window manager
  ansible.builtin.apt:
    name: i3
    state: present
  become: true
