---
- name: Download keyring.deb
  ansible.builtin.get_url:
    url: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2025.03.09_all.deb
    dest: /opt/keyring.deb
    checksum: sha256:2c2601e6053d5c68c2c60bcd088fa9797acec5f285151d46de9c830aaba6173c
    mode: "0600"
  become: true

- name: Install keyring.deb
  ansible.builtin.apt:
    deb: /opt/keyring.deb
  become: true

- name: Add sur5r repository
  ansible.builtin.apt_repository:
    repo: deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe
    state: present
    filename: sur5r
  become: true

- name: Install i3 window manager
  ansible.builtin.apt:
    name: i3
    state: present
  become: true
