---
- name: Install neovim
  become: true
  block:
    - name: Download latest stable tar archive
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        dest: /opt/nvim-linux64.tar.gz
        mode: "0777"

    - name: Extract neovim
      ansible.builtin.unarchive:
        src: /opt/nvim-linux64.tar.gz
        dest: /opt/

    - name: Create symbolic link for nvim
      ansible.builtin.file:
        src: /opt/nvim-linux64/bin/nvim
        dest: /usr/local/bin/nvim
        state: link
