---
- name: Configure init-templatedir
  vars:
    target_dir: "{{ home_directory }}/.git-template"
  block:
    - name: Check {{ target_dir }}
      ansible.builtin.stat:
        path: "{{ target_dir }}"
      register: template_dir

    - name: Pre-commit init
      ansible.builtin.command: pre-commit init-templatedir {{ target_dir }}
      args:
        creates: "{{ target_dir }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ home_directory }}/.local/bin"
      when: not template_dir.stat.exists
