---
- name: Check if .bashrc exists
  ansible.builtin.stat:
    path: "{{ home_directory }}/.bashrc"
  register: setup_bashrc_stat

- name: Backup old .bashrc
  ansible.builtin.copy:
    src: "{{ home_directory }}/.bashrc"
    dest: "{{ home_directory }}/.bashrc.bak"
    mode: preserve
  when: setup_bashrc_stat.stat.exists
  changed_when: false

- name: Remove .bashrc
  ansible.builtin.file:
    path: "{{ home_directory }}/.bashrc"
    state: absent
  changed_when: false

- name: Run stow command
  ansible.builtin.command: stow {{ item }}
  register: setup_output
  changed_when: setup_output.rc != 0
  args:
    chdir: "{{ home_directory }}/.dotfiles/"
  loop:
    - bash
    - blocksi3
    - git
    - i3
    - kitty
    - nvim
    - rofi
    - tmux
